# Paste your workflow YAML to this code editor
#Name of the work flow
name: First Workflow

#Trigger

on: 
  push        #event

jobs: 
  build:      #Job name
    runs-on: ubuntu-latest      #Hosted runner
    steps:
      -  name: Echo
         run: echo "Welcome to first workflow"

    
  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Echo
        run: echo "Welcome to first workflow" 
    
 
    
