name: CI For Maven Project Aspire batch


on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 

      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup Java JDK
        uses: actions/setup-java@v3.14.1
        with:
          java-version: 17
          distribution: microsoft
      - name: Build with Maven
        run: mvn --batch-mode  --update-snapshots verify
        working-directory: C:\Program Files\apache-maven-3.9.10 # <--- IMPORTANT: Modify this line
      - run: mkdir staging && cp target/*.jar staging
        working-directory: C:\Program Files\apache-maven-3.9.10 # <--- Add this line (if needed)
      - name: Upload a Build Artifact 
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Package
          path: staging
